FROM postgres:17.1-alpine

RUN mkdir -p /var/lib/postgresql/data && \
  chown -R postgres:postgres /var/lib/postgresql/data && \
  chmod 700 /var/lib/postgresql/data

USER ${POSTGRES_USER}

EXPOSE ${POSTGRES_PORT}

CMD ["postgres"]