FROM postgres:15-alpine

# ENV POSTGRES_USER=${POSTGRES_USER} \
#   POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
#   POSTGRES_DB=${POSTGRES_NAME}

# RUN mkdir -p /var/lib/postgresql/data && \
#   chown -R postgres:postgres /var/lib/postgresql/data && \
#   chmod 700 /var/lib/postgresql/data

USER postgres

EXPOSE 5432

CMD ["postgres"]